#pragma once

#define IDX_NOW "now"
#define IDX_TIME_STEP "time-step"
#define IDX_REAL_TIME "real-time"
#define IDX_WORLD "world"
#define IDX_SENSATION "sensation"
#define IDX_LOCATION "location"
#define IDX_POSITION "position"
#define IDX_POSITION_X "x"
#define IDX_POSITION_Y "y"
#define IDX_POSITION_Z "z"
#define IDX_ORIENTATION "orientation"
#define IDX_YAW "yaw"
#define IDX_PITCH "pitch"
#define IDX_VITAL "vital"
#define IDX_HEALTH "health"
#define IDX_FOOD "food"
#define IDX_WATER "water"
#define IDX_ENERGY "energy"
#define IDX_OXYGEN "oxygen"
#define IDX_HAND "hand"
#define IDX_ITEM "item"
#define IDX_ROUGHNESS "roughness"
#define IDX_HARDNESS "hardness"
#define IDX_OLFACTION "olfaction"
#define IDX_INTENSIVITY "intensivity"
#define IDX_FRIENDLYNESS "friendlyness"
#define IDX_EDIBLENESS "edibleness"
#define IDX_TOXICITY "toxicity"
#define IDX_VISUAL_FIELD "visual-field"
#define IDX_RANGE "range"
#define IDX_ANGLE "angle"
#define IDX_TACTILE_RANGE "tactile-range"
#define IDX_VISION "vision"
#define IDX_BLOCKS "blocks"
#define IDX_NEARBY "nearby"
#define IDX_TOUCH "touch"
#define IDX_ENTITIES "entities"
#define IDX_CARRY "carry"
#define IDX_INVENTORY "inventory"
#define IDX_LOCKER "locker"

#define IDX_ACTION "action"
#define IDX_BODY "body"
#define IDX_ROTATION "rotation"
#define IDX_TRANSLATION "translation"
#define IDX_SPEED "speed"
#define IDX_GESTURE "gesture"
#define IDX_REST "rest"
#define IDX_HEAD "head"
#define IDX_VERTICAL "vertical"
#define IDX_HORIZONTAL "horizontal"
#define IDX_ATTACK "attack"
#define IDX_STRONGNESS "strongness"
#define IDX_JUMP "jump"
#define IDX_HEIGHT "height"
#define IDX_INGEST "ingest"
#define IDX_THROW "throw"
#define IDX_CLIMB "climb"
#define IDX_GET_SLOT "get slot"
#define IDX_PUT_SLOT "put slot"
#define IDX_PRIMARY_ACTION "primary action" //It could be useful to say that an action was create by amygdala and which function in amygdala

#define PI 3.14159265
